#spring.application.name=todo
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/todos
    username: sizybar
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  messages:
    basename: messages,errors

debug: true
server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: error
    controllers: debug
    configurations: debug

